# Generated by Django 6.1 on 2026-09-09 21:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_creativeitem_order_orderitem_workentry_taskproposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeitem',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Must be approved by an admin before it appears in the public shop catalog.'),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('method', models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('bank', 'Bank')], max_length=20)),
                ('account_details', models.CharField(help_text='Bkash/Nagad phone number, or bank account number.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
