# Generated by Django 6.1 on 2026-09-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_creativeitem_is_approved_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('wallet', 'Wallet'), ('cod', 'Cash on Delivery'), ('sslz', 'SSLCommerz'), ('bank', 'Bank Account'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('card', 'Card')], max_length=20),
        ),
    ]
