# Generated by Django 6.1 on 2026-09-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_status_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('held_in_escrow', 'Held in Escrow'), ('released', 'Released'), ('refunded', 'Refunded'), ('completed', 'Completed')], default='held_in_escrow', max_length=20),
        ),
    ]
